version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: green_moment_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: green_moment
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: green_moment_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: green_moment_api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/green_moment
      - DATABASE_SYNC_URL=postgresql://postgres:password@db:5432/green_moment
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./:/app
      - /home/bill/StudioProjects/green_moment_integrated/stru_data:/carbon_data:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  celery:
    build: .
    container_name: green_moment_celery
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/green_moment
      - DATABASE_SYNC_URL=postgresql://postgres:password@db:5432/green_moment
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./:/app
      - /home/bill/StudioProjects/green_moment_integrated/stru_data:/carbon_data:ro
    command: celery -A app.core.celery_app worker --loglevel=info

  celery-beat:
    build: .
    container_name: green_moment_celery_beat
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/green_moment
      - DATABASE_SYNC_URL=postgresql://postgres:password@db:5432/green_moment
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./:/app
      - /home/bill/StudioProjects/green_moment_integrated/stru_data:/carbon_data:ro
    command: celery -A app.core.celery_app beat --loglevel=info

volumes:
  postgres_data:
  redis_data: